{
  "name": "{{ .PackageNS }}-client",
  "version": "0.1.0",
  "description": "Legacy JavaScript client for {{ .PackageNS }}",
  "author": "Generated by Ignite CLI",
  "dependencies": {
    "@starport/vue": "^0.23.0",
    "@starport/vuex": "^0.23.0",
    "axios": "^0.24.0"
  },
  "devDependencies": {
    "@vue/cli-service": "^4.5.0",
    "vue-template-compiler": "^2.6.11"
  },
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  }
}
